version: "3.6"

services:
  db:
    image: postgres:10.6-alpine
    environment:
      POSTGRES_DB: agriculture
    networks:
      - agriculture
    ports:
      - 5432:5432
    expose:
      - 5432
    # volumes:
    #   - postgres:/var/lib/postgresql/data

#   node_app:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     ports:
#       - "4000:4000"
#     depends_on:
#       - postgres


  adminer:
    image: adminer
    depends_on:
      - db
    environment:
      VIRTUAL_HOST: "db.agriculture.localtest.me"
      VIRTUAL_PORT: "8080"
    expose:
      - 8080
    networks:
      - agriculture

networks:
  agriculture: