version: '3'
services:
  node_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: grain-agriculture
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_DB: grain-agriculture
    secrets:
      - postgres_password

secrets:
  postgres_password:
    file: ./postgres_password.txt
